import { useState } from "react";

/**
 * ExportButtons — Download PDF, JSON, Print, Share
 */
export function ExportButtons({ score, recordingId }) {
  const [exporting, setExporting] = useState(false);

  const exportJSON = () => {
    const blob = new Blob([JSON.stringify(score, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `accentiq-report-${recordingId}.json`;
    a.click(); URL.revokeObjectURL(url);
  };

  const exportPDF = async () => {
    setExporting(true);
    try {
      const { jsPDF } = await import("jspdf");
      const pdf = new jsPDF("p", "mm", "a4");
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 15;
      let y = 20;

      // Title
      pdf.setFontSize(20);
      pdf.setTextColor(127, 29, 29); // maroon
      pdf.text("AccentIQ — Pronunciation Report", margin, y);
      y += 12;

      // Overall score
      pdf.setFontSize(14);
      pdf.setTextColor(30, 30, 30);
      pdf.text(`Overall Score: ${Math.round(score.overall_score)}/100`, margin, y);
      y += 8;

      // Sub-scores
      pdf.setFontSize(11);
      pdf.setTextColor(60, 60, 60);
      pdf.text(`Accuracy: ${Math.round(score.accuracy_score)}/100`, margin, y);
      pdf.text(`Fluency: ${Math.round(score.fluency_score)}/100`, margin + 60, y);
      y += 10;

      // Divider
      pdf.setDrawColor(200, 200, 200);
      pdf.line(margin, y, pageWidth - margin, y);
      y += 8;

      // Word scores
      if (score.word_scores && score.word_scores.length > 0) {
        pdf.setFontSize(12);
        pdf.setTextColor(30, 30, 30);
        pdf.text("Word-Level Analysis", margin, y);
        y += 7;

        pdf.setFontSize(9);
        const colWord = margin;
        const colScore = margin + 50;
        const colLabel = margin + 70;

        // Header
        pdf.setTextColor(100, 100, 100);
        pdf.text("Word", colWord, y);
        pdf.text("Score", colScore, y);
        pdf.text("Quality", colLabel, y);
        y += 5;

        pdf.setTextColor(40, 40, 40);
        for (const ws of score.word_scores) {
          if (y > 270) {
            pdf.addPage();
            y = 20;
          }
          const wordScore = Math.round(ws.score ?? ws.confidence * 100 ?? 0);
          const label = wordScore >= 80 ? "Good" : wordScore >= 60 ? "Needs work" : "Mispronounced";
          pdf.text(ws.word || "", colWord, y);
          pdf.text(String(wordScore), colScore, y);
          pdf.text(label, colLabel, y);
          y += 5;
        }
        y += 5;
      }

      // Divider
      if (y > 260) { pdf.addPage(); y = 20; }
      pdf.setDrawColor(200, 200, 200);
      pdf.line(margin, y, pageWidth - margin, y);
      y += 8;

      // AI Feedback
      if (score.feedback) {
        pdf.setFontSize(12);
        pdf.setTextColor(30, 30, 30);
        pdf.text("AI Feedback", margin, y);
        y += 7;
        pdf.setFontSize(9);
        pdf.setTextColor(60, 60, 60);
        const lines = pdf.splitTextToSize(score.feedback, pageWidth - 2 * margin);
        for (const line of lines) {
          if (y > 275) { pdf.addPage(); y = 20; }
          pdf.text(line, margin, y);
          y += 4.5;
        }
      }

      // Footer
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`Generated by AccentIQ · ${new Date().toLocaleDateString()}`, margin, 285);

      pdf.save(`accentiq-report-${recordingId}.pdf`);
    } catch (e) {
      console.error("PDF export error:", e);
      // Fallback to print
      window.print();
    } finally {
      setExporting(false);
    }
  };

  const handlePrint = () => window.print();

  const handleShare = async () => {
    const text = `My pronunciation score: ${Math.round(score.overall_score)}/100 (Accuracy: ${Math.round(score.accuracy_score)}, Fluency: ${Math.round(score.fluency_score)})`;
    if (navigator.share) {
      try { await navigator.share({ title: "AccentIQ Report", text }); } catch (_e) { /* user cancelled */ }
    } else {
      await navigator.clipboard.writeText(text);
      alert("Report summary copied to clipboard!");
    }
  };

  return (
    <div className="flex flex-wrap gap-2">
      <button className="btn-secondary !text-xs !px-3 !py-1.5" onClick={exportPDF} disabled={exporting}>
        {exporting ? "Exporting…" : "📄 PDF"}
      </button>
      <button className="btn-secondary !text-xs !px-3 !py-1.5" onClick={exportJSON}>
        📋 JSON
      </button>
      <button className="btn-secondary !text-xs !px-3 !py-1.5" onClick={handlePrint}>
        🖨️ Print
      </button>
      <button className="btn-secondary !text-xs !px-3 !py-1.5" onClick={handleShare}>
        🔗 Share
      </button>
    </div>
  );
}
